name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change to server directory
        run: cd server
      - name: Install dependencies
        run: npm ci
        working-directory: ./server
      - name: Build
        run: npm run build
        working-directory: ./server
      - name: Test
        run: npm run test
        working-directory: ./server
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./server/*
          remote_path: /var/www/gamebattle/
          remote_host: ec2-52-79-157-141.ap-northeast-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
